version: '3.8'

services:
  mysql-room-management-web:
    image: mysql:8.0
    container_name: mysql-room-management-web
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456789"
      MYSQL_DATABASE: "room-management-web"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --lower_case_table_names=1  # Thêm dòng này để cấu hình MySQL không phân biệt chữ hoa/thường

volumes:
  mysql_data:
