services:
  - type: web
    name: room-management-auth
    env: docker
    dockerfilePath: auth-service/Dockerfile
    buildCommand: |
      cd auth-service
      mvn clean package -DskipTests
      cd ..
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: room-management-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: room-management-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: room-management-db
          property: password
    plan: free

  - type: web
    name: room-management-main
    env: docker
    dockerfilePath: main-service/Dockerfile
    buildCommand: |
      cd main-service
      mvn clean package -DskipTests
      cd ..
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: room-management-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: room-management-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: room-management-db
          property: password
    plan: free

  - type: web
    name: room-management-file
    env: docker
    dockerfilePath: file-service/Dockerfile
    buildCommand: |
      cd file-service
      mvn clean package -DskipTests
      cd ..
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
    plan: free

  - type: web
    name: room-management-notify
    env: docker
    dockerfilePath: notify-service/Dockerfile
    buildCommand: |
      cd notify-service
      mvn clean package -DskipTests
      cd ..
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
    plan: free

  - type: web
    name: room-management-payment
    env: docker
    dockerfilePath: payment-service/Dockerfile
    buildCommand: |
      cd payment-service
      mvn clean package -DskipTests
      cd ..
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
    plan: free

databases:
  - name: room-management-db
    databaseName: room_management
    user: admin
    plan: free
