services:
  - type: web
    name: room-management-auth
    env: java
    build:
      dockerfile: ./auth-service/Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: room-management-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: room-management-db
          property: username
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: room-management-db
          property: password
    plan: free

  - type: web
    name: room-management-main
    env: java
    build:
      dockerfile: ./main-service/Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: room-management-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: room-management-db
          property: username
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: room-management-db
          property: password
    plan: free

  - type: web
    name: room-management-file
    env: java
    build:
      dockerfile: ./file-service/Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
    plan: free

  - type: web
    name: room-management-notify
    env: java
    build:
      dockerfile: ./notify-service/Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
    plan: free

  - type: web
    name: room-management-payment
    env: java
    build:
      dockerfile: ./payment-service/Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
    plan: free

databases:
  - name: room-management-db
    databaseName: room_management
    user: admin
    plan: free
    version: "8.0"
